[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
optimizer = true
viaIR = true

[fuzz]
runs = 10

[invariant]
runs = 10
depth = 10